#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

CONTAINER_NAME="decimate"
IMAGE_NAME="cenieto/${CONTAINER_NAME}"
ENTRYPOINT="/app"

usage(){
	printf "Usage:\n"
 	printf "\t build \t\t: Build container.\n"
 	printf "\t start \t\t: Deploy container.\n"
 	printf "\t stop \t\t: Destroy container.\n"
 	printf "\t shell \t\t: Open terminal shell inside container.\n"
	printf "\t run <params> \t: Run code.\n"
	printf "\t unit <params> \t: Run unit tests.\n"
 	printf "\t format \t\t: Format all go files.\n"
	printf "\t install \t\t: Install all dependencies.\n"
	printf "\t linting \t\t: Run linting.\n"

	exit 1
}

build_image(){
	docker build \
		--build-arg ENTRYPOINT=${ENTRYPOINT} \
		-t ${IMAGE_NAME} \
         .
}

start_or_stop_container() {
    local action=$1
	local image_tag=${2:-latest}

    if [[ "${action}" == "start" ]]; then
	
		docker rm -f ${CONTAINER_NAME} &> /dev/null # Purge before launch
		printf "Deploying ${CONTAINER_NAME} container...\n"
		docker run -d -it \
			--network host \
			--name "${CONTAINER_NAME}" \
			-v ${SCRIPT_DIR}:${ENTRYPOINT} \
			-w ${ENTRYPOINT} \
			--entrypoint top \
			${IMAGE_NAME}:${image_tag}

		until [ "`docker inspect -f {{.State.Status}} ${CONTAINER_NAME}`" == "running" ]; do
			sleep 0.5;
		done;

	elif [[ "${action}" == "stop" ]]; then
		docker rm -f ${CONTAINER_NAME} &> /dev/null # Purge before launch
	else
		echo "Error: action (allowed values: start, stop) can't be empty."
	fi
}

launch_shell(){
	docker exec -it $CONTAINER_NAME bash
}

unit_tests(){
	local params=${@}
	docker exec $CONTAINER_NAME bash -c "go test ${params}"
}

format_files(){
	docker exec $CONTAINER_NAME bash -c "gofmt -w ."
}

install_deps(){
	docker exec $CONTAINER_NAME bash -c "go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
}

exute_linting(){
	docker exec $CONTAINER_NAME bash -c "golangci-lint run"
}

execute_code(){
	local params=${@}

	docker exec $CONTAINER_NAME bash -c "go run ${params}"
}

case "$1" in

    build)
		build_image "${@:2}"
		;;
	start | stop)
        start_or_stop_container "${@:1}"
		;;
	unit)
        unit_tests "${@:2}"
		;;
	shell)
		launch_shell
		;;
	run)
		execute_code "${@:2}"
		;;
	format)
		format_files
		;;
	install)
		install_deps
		;;
	linting)
		exute_linting
		;;
	* | -h | help)
		usage
		;;
esac
