name: go-tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  CI:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Set script permissions
      run: chmod +x ./stack

    - name: Build image
      run: |
        ./stack build
        echo -n "verifying images:"
        docker images

    - name: Start test container
      run: |
        ./stack start

    - name: Install dependencies
      run: |
        ./stack install

    - name: Run linter
      run: |
        ./stack linting ./pkg/...

    - name: Run unit tests
      run: |
        ./stack unit ./pkg/... -covermode=count -coverprofile=coverage.out
        ./stack run go tool cover -func=coverage.out -o=coverage.out
    
    - name: Generate Coverage Badge
      uses: tj-actions/coverage-badge-go@v2
      with:
        filename: coverage.out

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-