name: go-tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  CI:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    # NOTE: this is for debugging only
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3

    - name: Build image
      run: |
        ./stack build
        echo -n "verifying images:"
        docker images

    - name: Start test container
      run: |
        ./stack start

    - name: Run unit tests
      run: |
        ./stack unit

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-